#!/bin/sh
#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t vizbattgit2 \
                         -C "start_jupyter -A -T @tool VizBATT.ipynb" \
                         -u PolyhedralAnalysis \
                          -r none \
                         -w headless
